import React, { FC } from 'react'
import styles from './MainLayout.module.css'
import {Navbar} from '../Navbar'
import Head from 'next/head'

type MainLayoutProps = {
  children: React.ReactNode
}

export const MainLayout: FC<MainLayoutProps> = ({children}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Home - Fer</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />
    
          <main className={styles.main}>
            {children}
          </main>
        </div>
      )
}
